#!/bin/bash
set -e

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
WEBSITE_DIR="$(cd "$DIR/.." >/dev/null 2>&1 && pwd)"
INFRA_DIR="$(cd "$WEBSITE_DIR/../infra-proyecto-colombia" >/dev/null 2>&1 && pwd)"
BACKEND_DIR="$(cd "$WEBSITE_DIR/../backend-proyecto-colombia" >/dev/null 2>&1 && pwd)"

echo "=========================================================="
echo "🇨🇴 Alojamiento Solidario Colombia — LocalStack Dev Runner"
echo "=========================================================="

# LocalStack env vars, needed by Terraform, the seed script, and the
# backend dev server — export before any of those run, not just before Next.js.
export NEXT_PUBLIC_API_URL="http://localhost:4000/api/listings"
export NEXT_PUBLIC_TURNSTILE_SITE_KEY="1x00000000000000000000AA"
export AWS_ENDPOINT_URL="http://localhost:4566"
export AWS_REGION="us-east-1"
export AWS_ACCESS_KEY_ID="test"
export AWS_SECRET_ACCESS_KEY="test"
export USE_LOCALSTACK="true"

# 1. Check Docker Daemon
if ! docker info >/dev/null 2>&1; then
  echo "❌ Error: Docker daemon is not running. Please launch Docker Desktop and try again."
  exit 1
fi

# 2. Check / Start LocalStack Container
echo "🐳 Checking LocalStack container..."
if ! docker ps --format '{{.Names}}' | grep -q "^proyecto-colombia-localstack$"; then
  echo "🚀 Starting LocalStack via docker-compose..."
  if [ -d "$BACKEND_DIR" ] && [ -f "$BACKEND_DIR/docker-compose.yml" ]; then
    (cd "$BACKEND_DIR" && docker compose up -d || docker-compose up -d)
  else
    (cd "$INFRA_DIR" && docker compose up -d || docker-compose up -d)
  fi
fi

echo "⏳ Waiting for LocalStack services on http://localhost:4566..."
MAX_RETRIES=30
COUNT=0
until curl -s http://localhost:4566/_localstack/health | grep -q "\"dynamodb\": \"\(running\|available\)\"" || [ $COUNT -eq $MAX_RETRIES ]; do
  sleep 1
  COUNT=$((COUNT+1))
done

if [ $COUNT -eq $MAX_RETRIES ]; then
  echo "⚠️ Warning: LocalStack took longer than expected to report healthy, continuing..."
fi

# 3. Apply Local Terraform Infrastructure (if infra directory exists)
#
# infra-proyecto-colombia hardcodes a prod S3 backend (provider.tf) with a
# DynamoDB lock table. `terraform init -backend=false` does NOT disable that
# backend — it only skips re-initializing it, so the cached prod backend stays
# active and `-state=` is silently ignored. Combined with the AWS_ENDPOINT_URL
# exported above, the prod lock request then lands in LocalStack, which has no
# such table. So: drop in a temporary override that genuinely forces local
# state, and use a separate TF_DATA_DIR so the prod .terraform/ backend cache
# is never clobbered.
if [ -d "$INFRA_DIR" ]; then
  echo "🏗️ Provisioning LocalStack Terraform infrastructure..."
  (
    cd "$INFRA_DIR"
    cat > local_backend_override.tf <<'TFEOF'
# Generated by website-proyecto-colombia/scripts/start-local-dev.sh.
# Forces local state so the prod S3/DynamoDB backend is never touched during
# LocalStack development. Removed automatically when the script exits.
terraform {
  backend "local" {
    path = "terraform.local.tfstate"
  }
}
TFEOF
    trap 'rm -f local_backend_override.tf' EXIT
    export TF_DATA_DIR=".terraform.local"
    terraform init -reconfigure -input=false >/dev/null
    terraform apply -var-file="environments/local.tfvars" -var="use_localstack=true" -auto-approve
  )
fi

# 4. Seed LocalStack DynamoDB Table via Backend
echo "🌱 Seeding sample Colombian emergency housing listings from backend-proyecto-colombia..."
(
  cd "$BACKEND_DIR"
  npm run seed:local
)

# 5. Trap cleanup on exit
cleanup() {
  echo -e "\n🛑 Shutting down Local Backend API Server..."
  if [ -n "$API_PID" ]; then
    kill "$API_PID" 2>/dev/null || true
  fi
  exit 0
}
trap cleanup SIGINT SIGTERM EXIT

# 6. Start TypeScript Backend Dev Server (Fastify) on port 4000
echo "⚡ Starting TypeScript Fastify Backend API on port 4000..."
(
  cd "$BACKEND_DIR"
  npm run dev
) &
API_PID=$!

# Wait for local API to respond
sleep 2

# 7. Start Next.js Development Server on port 3000
echo "🚀 Starting Next.js website on http://localhost:3000..."
cd "$WEBSITE_DIR"
npx next dev
